### ISSUE TITLE
Plugin manager

### ISSUE THREAD

**Issue by feddasch** [feddasch/koi#2]
Add an (optional) plugin manager to replace manual installations via Cargo/package manager, based on GitHub/GitLab releases

- [ ] Add a parser for a plugin file format
- [ ] Create an index repository for plugins
- [ ] Add a `plugin` subcommand

**Comment by feddasch** [comment]
Plugin file example:

`plugin.yml`:

```yaml
name       : git
# Short summary
summary    : Git integration plugin
description: | # Long description
  Git provides some commands that runs Git in the backstage.
plugdeps   : # Plugin dependencies
  - hello
extdeps    : # External dependencies (programs)
  - git
tarball    : # Tarball information
  matrix: # Tarball availability per target
    linux  : [64, 32]
    windows: [64, 32]
```
